### ISSUE TITLE
TO DO

### ISSUE THREAD

**Issue by mph55** [mph55/lanstation13#1]
- [x] Portar de volta a Baylight
- [x] Fazer "datums" para a música do lobby
- [x] Fazer "datums" para as lobby screens
- [x] Apagar as músicas do lobby do /vg/
- [x] Ligar o Travis e fazer ele mandar mensagens pro IRC correto
- [x] Fazer outro README
- [x] Adicionar o btime.so para os sistemas GNU/Linux
- [x] Adicionar a função para que as regras apareçam na primeira vez que jogador conecte ao servidor
- [x] Verdetexto no OOC
- [x] Arrumar os acentos
- [x] Adicionar a Mini2 aos mapas
- [x] Adicionar o alt-job de maid pro zelador
- [x] Garantir que a transição pro novo MC seja tranquila quando o mesmo entrar em uso no /vg/
- [x] Remover o *fart

**Comment by Gmaker2** [comment]
![screenshot_25](https://cloud.githubusercontent.com/assets/10011469/21753146/1984c802-d5c5-11e6-9c49-292e304593de.png)

**Comment by Gmaker2** [comment]
![screenshot_32](https://cloud.githubusercontent.com/assets/10011469/21753308/7532f288-d5c9-11e6-9375-dbe57e5580fc.png)
Você acha que isso vale o nosso tempo, anon?

**Comment by LadyApollo** [comment]
>baylight
Jesus cristo que horrível
