### ISSUE TITLE
Shaft miner precisa ser habilitado

### ISSUE THREAD

**Issue by mph55** [mph55/lanstation13#44]

**Comment by Gmaker2** [comment]
Por que?

**Comment by mph55** [comment]
Eu acho que é boa uma distinção pro RP fluir, assim a tripulação não pode ficar brava com um shaft miner por ele não aceitar as encomendas ou um cargo por ele trazer minérios

**Comment by Gmaker2** [comment]
Ok. Mas acredito que isso vai deixar o cargo sem ter o que fazer.
