### ISSUE TITLE
Maquinas de venda

### ISSUE THREAD

**Issue by OPrario** [mph55/lanstation13#53]
Troque ou adicione algumas maquinas de vendas por Groan's Soda e Discount Dan's.

**Comment by anao22** [comment]
Acho que tem uma Discount Dan perto da ciência, em baixo da Robótica

**Comment by OPrario** [comment]
Pior que tem mesmo.

**Comment by Gmaker2** [comment]
Nunca soube pra que a necessidade de maquinas diferentes. Só fui descobrir agora que serve para gheto chemistry.
