### ISSUE TITLE
Airlock para manutenção

### ISSUE THREAD

**Issue by anao22** [mph55/lanstation13#55]
#### Descrição do problema
Um cientista tem que andar muito para poder acessar a maint (isso é especialmente importante se acontecer uma radstorm).

Recomendo acrescentar uma porta em um dos lugares pintados de azul.
![mapa](https://cloud.githubusercontent.com/assets/24993519/22048539/79716704-dd0c-11e6-9f88-045298de681d.png)

**Comment by Gmaker2** [comment]
Concordo. Adicionarei.
