### ISSUE TITLE
Space Cleaner na medbay

### ISSUE THREAD

**Issue by anao22** [mph55/lanstation13#56]
Mesmo quando tem Zeladores, a Medbay fica uma bagunça. Colocar pelo menos um space cleaner (mesmo que vazio) na medbay, para limpar a sujeira provocada por todo mundo.

**Comment by Gmaker2** [comment]
O morphi retirou propositalmente os space cleaners da estação pois "ficaria muito fácil". Acho que ele já deve ter mudado de ideia.

**Comment by mph55** [comment]
Sim, coloque um space cleaner vazio e uma barra de sabão
