### ISSUE TITLE
Arcade/Sigarros na frente da placa do bar

### ISSUE THREAD

**Issue by anao22** [mph55/lanstation13#57]
É preciso retirar um para poder mudar o nome do bar
![1](https://cloud.githubusercontent.com/assets/24993519/22092790/5632438e-dddf-11e6-9da7-3e7af64bd089.png)
![2](https://cloud.githubusercontent.com/assets/24993519/22092791/5659a172-dddf-11e6-8bf9-bbc8b30404e3.png)

**Comment by mph55** [comment]
Dá pra mudar a placa do bar do lado direito do arcade ou do lado de fora do bar

**Comment by Gmaker2** [comment]
O morphi já falou que dá para mudar tranquilamente com os dois aí. Por mim pode fechar esse issue.
