### ISSUE TITLE
Revisão do número de pessoas em cada job

### ISSUE THREAD

**Issue by Gmaker2** [mph55/lanstation13#63]
Engenheiros precisam ser reduzidos para no máximo dois.
Não precisamos de mais de um roboticista.
Três botanistas é um exagero para uma botânica tão pequena.
Clowns, se já não forem, devem ser únicos
Agora que miners foram adicionados, eles e os cargo techs devem ser revistos.

**Comment by mph55** [comment]
Dois mineiros e um cargo está bom?

**Comment by Gmaker2** [comment]
Acredito que sim.

**Comment by anao22** [comment]
O problema é se o Cargo ficar braindead, o que é bem comum porque é um emprego pra newfags
